name: DeployBot
on:
  pull_request:
  push:
    branches:
      - '*'
jobs:
  auto-commit:
    if: github.event.release.tag_name == 'deployBot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.API_TOKEN_GITHUB }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: DeployBot
          commit_message: 'Deploy to Vercel'
          commit_options: '--no-verify --allow-empty'
          commit_author: Author <actions@github.com>
          skip_dirty_check: true
