name: Vercel Deployment
on:
  pull_request:
  push:
    branches:
      - '*'
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Vercel Deployment
          commit_options: '--no-verify --allow-empty'
          token: ${{ secrets.API_TOKEN_GITHUB }}

