 
 name: DeployBot
on:
  pull_request:
  push:
    branches:
      - '*'
jobs:
  auto-commit:
    if: github.event.commits[0].author.name != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ github.event.commits[0].author.name }}
        run: echo "$GITHUB_CONTEXT"
