name: Vercel depl
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add commit to any branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b ${{ github.ref }}
          git commit --allow-empty -m "Vercel deployment"
          git push origin ${{ github.ref }}
